package com.slangbridge.backend.config;

import com.slangbridge.backend.model.Slang;
import com.slangbridge.backend.repository.SlangRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

@Configuration
public class DataLoader {

    @Bean
    CommandLineRunner loadData(SlangRepository repo) {
        return args -> {

            List<Slang> seedData = List.of(
                    new Slang(null, "lol", "Laughing out loud", "That video made me lol."),
                    new Slang(null, "lmao", "Laughing very hard", "I saw the blooper and lmao."),
                    new Slang(null, "rofl", "Rolling on the floor laughing", "The meme had me rofl."),
                    new Slang(null, "rizz", "Charm or flirting ability", "He has insane rizz."),
                    new Slang(null, "mid", "Mediocre or unimpressive", "The movie was mid."),
                    new Slang(null, "bussin", "Tastes extremely good", "This pasta is bussin."),
                    new Slang(null, "fr", "For real; seriously", "You're coming? fr."),
                    new Slang(null, "sus", "Suspicious or questionable", "He was acting sus."),
                    new Slang(null, "ong", "On God; strong agreement", "That place had the best fries ong."),
                    new Slang(null, "no cap", "Not lying; being honest", "That test was brutal no cap."),
                    new Slang(null, "cap", "Lie or exaggeration", "That's cap, he wasn't there."),
                    new Slang(null, "bet", "Agreement or acceptance", "Want to meet at 7? bet."),
                    new Slang(null, "deadass", "Completely serious", "I'm deadass tired."),
                    new Slang(null, "ate", "Did exceptionally well", "She ate during her performance."),
                    new Slang(null, "extra", "Over the top or dramatic", "He's so extra about birthdays."),
                    new Slang(null, "pressed", "Annoyed or frustrated", "Why are you so pressed about it?"),
                    new Slang(null, "lowkey", "Somewhat or subtly", "I'm lowkey excited for tomorrow."),
                    new Slang(null, "highkey", "Openly or obviously", "I'm highkey ready for summer."),
                    new Slang(null, "vibe", "Atmosphere or emotional feel", "This cafe has such a good vibe."),
                    new Slang(null, "goat", "Greatest of all time", "Serena is the goat."),
                    new Slang(null, "pog", "Excitement or praise (gaming)", "You got the rare drop, pog!"),
                    new Slang(null, "poggers", "Excitement expressed in gaming streams", "That clutch was poggers!"),
                    new Slang(null, "irl", "In real life", "We finally met irl."),
                    new Slang(null, "afk", "Away from keyboard", "Hold up, I'm afk for a sec."),
                    new Slang(null, "gg", "Good game", "We lost but gg."),
                    new Slang(null, "wp", "Well played (gaming)", "Nice flank, wp."),
                    new Slang(null, "ez", "Easy win or task", "That match was ez."),
                    new Slang(null, "clutch", "Performed under pressure successfully", "He hit the clutch shot."),
                    new Slang(null, "ghosting", "Cutting off communication without explanation", "After the interview they ghosted me."),
                    new Slang(null, "salty", "Bitter or annoyed", "He's salty about losing."),
                    new Slang(null, "fit", "Outfit or clothing style", "Your fit is clean."),
                    new Slang(null, "drip", "Stylish clothing or accessories", "He's got the drip."),
                    new Slang(null, "flex", "Show off", "He's flexing his new sneakers."),
                    new Slang(null, "tea", "Gossip or interesting news", "Spill the tea about last night."),
                    new Slang(null, "spilling", "Revealing gossip", "We're spilling today."),
                    new Slang(null, "valid", "Cool or acceptable", "That jacket is valid."),
                    new Slang(null, "based", "Unapologetically authentic opinion", "She said it straight, very based."),
                    new Slang(null, "ratio", "When replies outweigh likes (social media)", "He got ratioed instantly."),
                    new Slang(null, "stan", "Intense fan or supporter", "He's a Billie Eilish stan."),
                    new Slang(null, "simp", "Person who shows excessive devotion to someone", "He's simping again."),
                    new Slang(null, "main character", "Person perceived at center of attention", "She's got main character energy."),
                    new Slang(null, "energy", "Distinct vibe or attitude", "He's got mentor energy."),
                    new Slang(null, "yeet", "Throw forcefully or express excitement", "He yeeted the ball."),
                    new Slang(null, "slaps", "Sounding excellent, usually music", "This track slaps."),
                    new Slang(null, "fire", "Very good or impressive", "Your artwork is fire."),
                    new Slang(null, "heated", "Angry or emotionally intense", "The argument got heated."),
                    new Slang(null, "big yikes", "Strong embarrassment reaction", "Forgetting the lines was big yikes."),
                    new Slang(null, "yikes", "Mild embarrassment reaction", "That comment was yikes."),
                    new Slang(null, "bruh", "Expression of disbelief or disappointment", "Bruh, not again."),
                    new Slang(null, "ok boomer", "Dismissive retort to outdated opinions", "Okay boomer, calm down."),
                    new Slang(null, "snatched", "Looks excellent or well styled", "Your hair is snatched today."),
                    new Slang(null, "bop", "Catchy or enjoyable song", "This chorus is a bop."),
                    new Slang(null, "lag", "Delay or slowdown (tech)", "My ping is causing lag."),
                    new Slang(null, "ping", "Network response time", "Your ping is spiking hard."),
                    new Slang(null, "buffed", "Improved in ability (gaming)", "That character got buffed."),
                    new Slang(null, "nerfed", "Made weaker (gaming)", "They nerfed the sniper."),
                    new Slang(null, "hardcarry", "Single player ensures success", "He hardcarried the match."),
                    new Slang(null, "malding", "Mad and balding (joking insult)", "The streamer was malding after losing."),
                    new Slang(null, "touch_grass", "Go outside, reconnect with reality", "Log off and touch grass."),
                    new Slang(null, "vaxxed", "Vaccinated", "I’m fully vaxxed now."),
                    new Slang(null, "clouty", "Chasing clout", "That post is too clouty."),
                    new Slang(null, "snacc", "Attractive person", "Did you see that snacc at the party?"),
                    new Slang(null, "drippin", "Wearing stylish clothes", "He’s drippin today."),
                    new Slang(null, "gasoline", "Extremely hype or exciting", "That concert was gasoline."),
                    new Slang(null, "shrekt", "Destroyed completely (humorous)", "He got shrekt in the debate."),
                    new Slang(null, "finessed", "Skillfully handled situation", "She finessed the tickets."),
                    new Slang(null, "stanned", "Strongly supported", "We stanned that artist."),
                    new Slang(null, "litty", "Very exciting or fun", "The party was litty."),
                    new Slang(null, "okurrr", "Emphatic approval or excitement", "She said okurrr to the idea."),
                    new Slang(null, "gassed", "Excited or hyped up", "He’s gassed for the game."),
                    new Slang(null, "suspect", "Suspicious or questionable", "That move seems suspect."),
                    new Slang(null, "npc", "Acting without agency or originality", "Bro is acting like an NPC."),
                    new Slang(null, "humble_flex", "Showing off subtly", "Posting those trophies is a humble flex."),
                    new Slang(null, "vibes", "Mood or atmosphere", "The vibes are good tonight."),
                    new Slang(null, "slay", "Perform with excellence or confidence", "She slayed that role."),
                    new Slang(null, "buggin", "Acting irrationally", "Why are you buggin over nothing?"),
                    new Slang(null, "locked_in", "Focused and determined", "He's locked in for finals."),
                    new Slang(null, "frfr", "For real for real (emphasis)", "I'm tired frfr."),
                    new Slang(null, "mother", "Title for a beloved female performer", "Beyoncé is mother."),
                    new Slang(null, "father", "Admired male performer or leader", "Keanu Reeves is father."),
                    new Slang(null, "spooked", "Startled or alarmed", "That jump scare spooked me."),
                    new Slang(null, "girlboss", "Woman asserting power with confidence", "She girlbossed the entire pitch."),
                    new Slang(null, "gatekeep_gaslight", "Meme combo of manipulative behaviors", "He tried to gaslight and gatekeep."),
                    new Slang(null, "understood_the_assignment", "Delivered exactly what was needed", "She understood the assignment."),
                    new Slang(null, "brain_empty", "No thoughts or mental clarity", "After exams my brain is empty."),
                    new Slang(null, "crying_screaming", "Extreme laughter reaction", "That edit has me crying screaming."),
                    new Slang(null, "low_effort", "Minimal investment or quality", "That meme was low effort."),
                    new Slang(null, "high_effort", "Substantial work or attention to detail", "This cosplay is high effort."),
                    new Slang(null, "tbh", "To be honest", "TBH I liked the OG version better."),
                    new Slang(null, "iktr", "I know that’s right", "IKTR she snapped."),
                    new Slang(null, "iykyk", "If you know you know", "This spot hits, IYKYK."),
                    new Slang(null, "oomf", "One of my followers", "OOMF went viral today."),
                    new Slang(null, "rent_free", "Occupying thoughts without consent", "That song lives rent free in my head."),
                    new Slang(null, "cookbook", "Collection of strategies or tactics", "He shared his chess cookbook."),
                    new Slang(null, "slumped", "Completely exhausted or asleep", "After gym I was slumped."),
                    new Slang(null, "sturdy", "Stylish dance trend or solid footing", "He got sturdy at the party."),
                    new Slang(null, "ate_down", "Performed extremely well with emphasis", "She ate down during rehearsals."),
                    new Slang(null, "giving", "Evoking a particular aesthetic", "This outfit is giving vintage."),
                    new Slang(null, "touch_starved", "Lacking physical affection (light slang)", "Being single got me touch starved."),
                    new Slang(null, "screaming", "Strong laughter reaction", "I'm screaming at that meme."),
                    new Slang(null, "pookie", "Playful nickname for friend", "Relax pookie, it's fine."),
                    new Slang(null, "bestie", "Close friend", "Calm down bestie."),
                    new Slang(null, "fan_cam", "Edited video highlighting a person", "The fan cam went viral."),
                    new Slang(null, "canon_event", "Inevitable formative experience", "Heartbreak is a canon event."),
                    new Slang(null, "locked", "Committed or secured", "We’re locked for tomorrow."),
                    new Slang(null, "strap_in", "Prepare for intensity", "Strap in, midterms are here."),
                    new Slang(null, "red_flag", "Warning sign of bad behavior", "Interrupting everyone is a red flag."),
                    new Slang(null, "green_flag", "Positive trait or healthy behavior", "Good communication is a green flag."),
                    new Slang(null, "drained", "Emotionally or mentally exhausted", "I feel drained after back-to-back meetings."),
                    new Slang(null, "brain_fog", "Reduced mental clarity", "The cold medicine gave me brain fog."),
                    new Slang(null, "played_out", "Overused or unoriginal", "That trend is played out."),
                    new Slang(null, "cook_session", "Period of focused productivity", "We had a whole cook session on the project."),
                    new Slang(null, "zoned_out", "Detached or unfocused mentally", "I zoned out during the lecture."),
                    new Slang(null, "overthinking", "Thinking excessively about a situation", "I’m overthinking that message."),
                    new Slang(null, "spin_back", "Return after leaving", "He said he’d spin back tomorrow."),
                    new Slang(null, "zoomies", "Sudden burst of energy", "The dog got zoomies at midnight."),
                    new Slang(null, "shadow_realm", "Humorously severe exile", "That argument sent him to the shadow realm."),
                    new Slang(null, "clapped_back", "Responded sharply to criticism", "She clapped back at the comments."),
                    new Slang(null, "villain_arc", "Period of acting unapologetically", "She entered her villain arc post breakup."),
                    new Slang(null, "side_quest", "Minor, optional activity", "Cleaning my room instead of homework was a side quest."),
                    new Slang(null, "plot_twist", "Unexpected development", "That exam had a plot twist ending."),
                    new Slang(null, "skill_issue", "Fault attributed to lack of skill", "He failed—skill issue."),
                    new Slang(null, "built_diff", "Exceptionally capable", "She’s built diff academically."),
                    new Slang(null, "study_grind", "Focused academic work", "Back on the study grind."),
                    new Slang(null, "caffeine_buff", "Temporary enhancement from caffeine", "I need a caffeine buff before class."),
                    new Slang(null, "downtime", "Resting period between tasks", "Using lunchtime as downtime."),
                    new Slang(null, "casuals", "People not deeply invested in hobby", "That game mode is full of casuals."),
                    new Slang(null, "meta", "Most effective strategy available", "Shield spam is the current meta."),
                    new Slang(null, "overbuffed", "Improved too much", "That spell is overbuffed now."),
                    new Slang(null, "matchmade", "Paired for activity or competition", "We got matchmade instantly."),
                    new Slang(null, "clutched", "Succeeded under pressure", "She clutched the last question."),
                    new Slang(null, "reverse_sweep", "Comeback from losing position", "The team pulled a reverse sweep."),
                    new Slang(null, "breakpoint", "Critical turning moment", "Finals are my breakpoint."),
                    new Slang(null, "no_brainer", "Obvious choice", "Taking that bonus was a no brainer."),
                    new Slang(null, "overkill", "Excessive effort beyond necessity", "Studying 12 hours was overkill."),
                    new Slang(null, "underwhelmed", "Unimpressed beyond expectation", "The finale left me underwhelmed."),
                    new Slang(null, "mid_tier", "Moderately average quality", "That café was mid tier."),
                    new Slang(null, "top_tier", "Highest ranking quality", "Her notes are top tier."),
                    new Slang(null, "hard_pass", "Strong refusal", "Going out in that cold is a hard pass."),
                    new Slang(null, "soft_launch", "Subtle introduction of something new", "Posting hints was a soft launch."),
                    new Slang(null, "hard_launch", "Direct and public introduction", "He hard launched the new project."),
                    new Slang(null, "peak", "Optimal or best state", "Dinner tonight was peak."),
                    new Slang(null, "valley", "Low or suboptimal state", "Last semester was a valley."),
                    new Slang(null, "pain_arc", "Period defined by hardship", "Midterms started the pain arc."),
                    new Slang(null, "buffed_confidence", "Temporary increase in confidence", "New shoes buffed my confidence."),
                    new Slang(null, "nerd_sniped", "Distracted by an interesting detail", "I got nerd sniped by that puzzle."),
                    new Slang(null, "wonky", "Unstable or slightly off", "The screen looks wonky."),
                    new Slang(null, "tweaking", "Acting restless or irrational", "He was tweaking over the test."),
                    new Slang(null, "bricked", "Rendered nonfunctional", "My phone bricked mid update."),
                    new Slang(null, "jank", "Low quality but functional", "The setup is jank but works."),
                    new Slang(null, "patched_up", "Improvised repair", "We patched up the bike with tape."),
                    new Slang(null, "dropped_ball", "Failed responsibility", "The team dropped the ball on planning."),
                    new Slang(null, "off_radar", "Unavailable or unresponsive", "He went off radar all weekend."),
                    new Slang(null, "on_radar", "Noticed or tracked for attention", "That idea is on my radar now."),
                    new Slang(null, "sniped", "Taken quickly before others", "He sniped the last cookie."),
                    new Slang(null, "stacked", "Equipped with many advantages", "Her schedule is stacked today."),
                    new Slang(null, "overbooked", "Scheduled beyond reasonable capacity", "I’m overbooked tomorrow."),
                    new Slang(null, "underbooked", "Scheduled with minimal tasks", "Next week is underbooked."),
                    new Slang(null, "ghosted", "Sudden cutoff of communication", "She ghosted me after the party."),
                    new Slang(null, "clout heavy", "Having strong online influence", "His account is clout heavy."),
                    new Slang(null, "mood", "Relatable feeling or vibe", "That song is such a mood."),
                    new Slang(null, "rager", "Wild party", "Last night’s rager was insane."),
                    new Slang(null, "cancelled", "Rejected or boycotted", "That movie got cancelled online."),
                    new Slang(null, "receipts", "Evidence for a claim", "Show me the receipts."),
                    new Slang(null, "slide_in_dms", "Message someone privately", "He tried to slide in DMs."),
                    new Slang(null, "flexing_on", "Showing off to someone", "He’s flexing on everyone."),
                    new Slang(null, "hold_tea", "Keep information secret for gossip", "I’ll hold the tea for now."),
                    new Slang(null, "spicy_take", "Controversial opinion", "That’s a spicy take."),
                    new Slang(null, "shook", "Surprised or shaken", "I was shook by the ending."),
                    new Slang(null, "bamboozled", "Tricked or fooled", "I got bamboozled in the game."),
                    new Slang(null, "sniped_out", "Eliminated quickly", "He got sniped out early."),
                    new Slang(null, "ready_set_go", "Immediate start", "Ready, set, go!"),
                    new Slang(null, "level_up", "Progress to next stage", "I finally leveled up."),
                    new Slang(null, "power_move", "Strategic impressive action", "Quitting early was a power move."),
                    new Slang(null, "combo_breaker", "Interruption of momentum", "That crit was a combo breaker."),
                    new Slang(null, "next_level", "Surpassing previous standard", "This new track is next level."),
                    new Slang(null, "cheugy", "Outdated or trying too hard", "Those shoes are cheugy."),
                    new Slang(null, "sus_af", "Extremely suspicious", "That behavior is sus af."),
                    new Slang(null, "big_mood", "Strongly relatable feeling", "That nap is big mood."),
                    new Slang(null, "extra_af", "Excessively dramatic", "He’s extra af about the announcement."),
                    new Slang(null, "shooketh", "Exaggerated shocked expression", "I was shooketh after the finale."),
                    new Slang(null, "capper", "Person who lies", "Don’t trust him, he’s a capper."),
                    new Slang(null, "hitdifferent", "Unique or unusually good experience", "This coffee hitsdifferent."),
                    new Slang(null, "sksksk", "Excited or laughing expression", "She typed sksksk in chat."),
                    new Slang(null, "and_i_oop", "Reaction to unexpected event", "And I oop, she fell."),
                    new Slang(null, "living_my_best_life", "Feeling content and fulfilled", "I’m living my best life today."),
                    new Slang(null, "stan_account", "Dedicated fan account", "This stan account tweets only BTS content."),
                    new Slang(null, "bussin_ass", "Extremely good", "This pizza is bussin ass."),
                    new Slang(null, "drip_check", "Assessing style or fashion", "We did a drip check in class."),
                    new Slang(null, "clout_chaser", "Person seeking attention or fame", "He’s a clout chaser online."),
                    new Slang(null, "sus_brain", "Suspiciously thinking", "That’s sus brain logic."),
                    new Slang(null, "simped_out", "Overly devoted", "He simped out for the whole team."),
                    new Slang(null, "yeeted_out", "Thrown or discarded", "That ball got yeeted out of the court."),
                    new Slang(null, "flexin_hard", "Showing off aggressively", "He’s flexin hard with his new car."),
                    new Slang(null, "drip_tier", "Level of style", "That outfit is drip tier."),
                    new Slang(null, "gaslighted", "Manipulated emotionally", "She got gaslighted in the argument."),
                    new Slang(null, "chefs_kiss", "Perfect execution", "The presentation was chefs kiss."),
                    new Slang(null, "main_char_energy", "Dominant presence", "He walked in with main char energy."),
                    new Slang(null, "snacc_alert", "Noticing someone attractive", "Snacc alert by the lockers."),
                    new Slang(null, "vaxxed_up", "Fully vaccinated", "I’m vaxxed up and ready."),
                    new Slang(null, "big_brain", "High intelligence or insight", "That solution was big brain."),
                    new Slang(null, "canceled_af", "Completely rejected or boycotted", "That idea is canceled af."),
                    new Slang(null, "lit_as_f", "Extremely exciting or fun", "The concert was lit as f."),
                    new Slang(null, "sksksk_and_i_oop", "Excited chaotic reaction", "Sksksk and I oop, she tripped."),
                    new Slang(null, "mood_af", "Relatable strong feeling", "That nap is mood af."),
                    new Slang(null, "glowed_up", "Improved appearance dramatically", "She really glowed up this year."),
                    new Slang(null, "thicc", "Curvy or full-bodied", "That character is thicc."),
                    new Slang(null, "thirsty", "Desperate for attention", "He’s thirsty for clout."),
                    new Slang(null, "capper_detected", "Caught lying", "Capper detected, he’s lying."),
                    new Slang(null, "simp_alert", "Noticeable simping behavior", "Simp alert in the chat."),
                    new Slang(null, "chugged", "Consumed rapidly", "He chugged the soda."),
                    new Slang(null, "ratchet", "Loud or wild behavior", "That party got ratchet."),
                    new Slang(null, "throwing_shade", "Subtle insult or criticism", "She’s throwing shade at him."),
                    new Slang(null, "wig", "Mind blown expression", "Wig, that plot twist."),
                    new Slang(null, "hunty", "Playful insult or term of endearment", "You better not, hunty."),
                    new Slang(null, "on_fleek", "Perfectly styled or executed", "Eyebrows on fleek today."),
                    new Slang(null, "slay_queen", "Confident, excellent woman", "She’s a true slay queen."),
                    new Slang(null, "slay_king", "Confident, excellent man", "He’s a slay king."),
                    new Slang(null, "tea_spilled", "Gossip revealed", "The tea’s spilled now."),
                    new Slang(null, "snatched_edges", "Perfectly styled hair edges", "Her edges are snatched."),
                    new Slang(null, "woke", "Socially aware", "She’s woke about climate issues."),
                    new Slang(null, "capper_move", "Dishonest or fake action", "That was a capper move."),
                    new Slang(null, "ok_boomer", "Dismissive response to older opinion", "Ok boomer, sure."),
                    new Slang(null, "simp_mode", "Acting overly devoted", "He’s in simp mode today."),
                    new Slang(null, "midly_amused", "Slightly entertained", "I’m midly amused by this."),
                    new Slang(null, "litty_fam", "Extremely fun with friends", "The party was litty fam."),
                    new Slang(null, "skrrt", "Sound of car acceleration; excited reaction", "Skrrt, we’re leaving."),
                    new Slang(null, "wavy", "Cool or stylish vibe", "That beat is wavy."),
                    new Slang(null, "hits_different", "Feels unique or exceptional", "This song hits different."),
                    new Slang(null, "finna", "Going to (slang)", "I’m finna leave."),
                    new Slang(null, "bet_that", "Strong agreement", "Bet that, I’m in."),
                    new Slang(null, "litty_af", "Extremely fun or exciting", "The festival was litty af."),
                    new Slang(null, "slaps_hard", "Very good, impactful", "This remix slaps hard."),
                    new Slang(null, "clap_back", "Respond sharply to criticism", "She clapped back at the trolls."),
                    new Slang(null, "popped_off", "Performed exceptionally", "He popped off during the game."),
                    new Slang(null, "hit_em_up", "Attack verbally or jokingly", "He hit em up in chat."),
                    new Slang(null, "sus_move", "Suspicious action", "That was a sus move."),
                    new Slang(null, "clouted_up", "Boosted in influence", "He clouted up after the viral post."),
                    new Slang(null, "main_char", "Dominant central figure", "She’s the main char in the group."),
                    new Slang(null, "spicy", "Exciting or controversial", "That take is spicy."),
                    new Slang(null, "juice", "Influence or respect", "He’s got the juice in class."),
                    new Slang(null, "gucci", "All good or fine", "Everything’s gucci."),
                    new Slang(null, "troll_mode", "Acting mischievously online", "He’s in troll mode today."),
                    new Slang(null, "weirdflex", "Odd display of pride", "That’s a weird flex."),
                    new Slang(null, "weirdflex_but_ok", "Odd display of pride, but acceptable", "Weird flex but ok."),
                    new Slang(null, "snap", "Surprised or impressed reaction", "Snap! That’s insane."),
                    new Slang(null, "lit_go", "Excitedly go", "Litty, let’s lit go!"),
                    new Slang(null, "heat_check", "Assessing strength or quality", "Time for a heat check on the beats."),
                    new Slang(null, "drip_check_done", "Style confirmed", "Drip check done, looking good."),
                    new Slang(null, "snack_mode", "Noticing someone attractive", "Snack mode activated."),
                    new Slang(null, "yass", "Excited affirmation", "Yass queen!"),
                    new Slang(null, "boss_up", "Level up or take control", "It’s time to boss up."),
                    new Slang(null, "yeeted", "Thrown with force", "He yeeted the ball."),
                    new Slang(null, "big_brain_move", "Intelligent action", "That was a big brain move."),
                    new Slang(null, "hitdifferent_now", "Now feels exceptional", "This flavor hitsdifferent now."),
                    new Slang(null, "mood_now", "Current feeling is relatable", "Nap time is mood now."),
                    new Slang(null, "glow_up_now", "Improved appearance presently", "She glowed up now."),
                    new Slang(null, "snatched_now", "Looks perfect currently", "Edges are snatched now."),
                    new Slang(null, "gassed_up", "Excited or hyped", "He’s gassed up for the event."),
                    new Slang(null, "flex_hard", "Show off aggressively", "Flex hard with those gains."),
                    new Slang(null, "drip_now", "Stylish currently", "Drip now, outfit complete."),
                    new Slang(null, "heat_now", "High energy or hype", "The room is heat now."),
                    new Slang(null, "pog_now", "Excitement right now", "Pog now, that’s insane.")
            );


            // pull existing terms once
            Set<String> existing = repo.findAll()
                    .stream()
                    .map(s -> s.getTerm().toLowerCase())
                    .collect(Collectors.toSet());

            // filter out duplicates before insert
            List<Slang> newOnes = seedData.stream()
                    .filter(s -> !existing.contains(s.getTerm().toLowerCase()))
                    .toList();

            if (!newOnes.isEmpty()) {
                repo.saveAll(newOnes);
            }
        };
    }
}
