package com.slangbridge.backend.config;

import com.slangbridge.backend.model.Slang;
import com.slangbridge.backend.repository.SlangRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class DataLoader {
    @Bean
    CommandLineRunner loadData(SlangRepository repo) {
        return (args) -> {
            repo.save(new Slang((Long)null, "cooked", "Completely exhausted or defeated", "After finals week, I was absolutely cooked."));
            repo.save(new Slang((Long)null, "bet", "Agreement or confirmation", "You’re coming at 8? Bet."));
            repo.save(new Slang((Long)null, "ghosted", "Suddenly ignored without explanation", "They stopped replying—I got ghosted."));
            repo.save(new Slang((Long)null, "rizz", "Charm or flirting ability", "That dude has insane rizz."));
            repo.save(new Slang((Long)null, "lowkey", "Quietly or secretly", "I lowkey love that song."));
            repo.save(new Slang((Long)null, "highkey", "Very openly or strongly", "I highkey need sleep."));
            repo.save(new Slang((Long)null, "sus", "Suspicious or questionable", "Why are you acting so sus?"));
            repo.save(new Slang((Long)null, "mid", "Average or unimpressive", "The movie was mid."));
            repo.save(new Slang((Long)null, "W", "Win or success", "That test grade is a W."));
            repo.save(new Slang((Long)null, "L", "Loss or failure", "Missing the bus was an L."));
            repo.save(new Slang((Long)null, "npc", "Someone who lacks awareness", "Bro moves like an NPC."));
            repo.save(new Slang((Long)null, "cap", "Lie or exaggeration", "That story is cap."));
            repo.save(new Slang((Long)null, "no cap", "No lie, being honest", "This food is good, no cap."));
            repo.save(new Slang((Long)null, "main character", "Someone acting like life centers on them", "She’s in her main character era."));
            repo.save(new Slang((Long)null, "slaps", "Is very good", "That song slaps."));
            repo.save(new Slang((Long)null, "dead", "Something extremely funny", "That joke had me dead."));
            repo.save(new Slang((Long)null, "touch grass", "Go outside and be realistic", "Bro needs to touch grass."));
            repo.save(new Slang((Long)null, "bricked", "Unable to function or frozen", "My laptop is bricked."));
            repo.save(new Slang((Long)null, "vibe", "Atmosphere or feeling", "This place has good vibes."));
            repo.save(new Slang((Long)null, "fire", "Excellent or impressive", "That outfit is fire."));
            repo.save(new Slang((Long)null, "extra", "Over-the-top behavior", "You’re doing too much, that’s extra."));
            repo.save(new Slang((Long)null, "salty", "Bitter or upset", "He’s salty about losing."));
            repo.save(new Slang((Long)null, "flex", "Show off", "That was a weird flex."));
            repo.save(new Slang((Long)null, "clapped", "Broken or ruined", "My sleep schedule is clapped."));
            repo.save(new Slang((Long)null, "bussin", "Really good (food)", "This burger is bussin."));
            repo.save(new Slang((Long)null, "drip", "Stylish outfit", "His drip is clean."));
            repo.save(new Slang((Long)null, "ick", "Sudden feeling of disgust", "That gave me the ick."));
            repo.save(new Slang((Long)null, "ratio", "More negative reactions than positive", "Your post got ratioed."));
            repo.save(new Slang((Long)null, "soft launch", "Subtle reveal", "She soft-launched her relationship."));
            repo.save(new Slang((Long)null, "hard launch", "Obvious reveal", "They hard-launched on Instagram."));
            repo.save(new Slang((Long)null, "delulu", "Delusional thinking", "Staying delulu is the solulu."));
            repo.save(new Slang((Long)null, "ate", "Did extremely well", "She ate that presentation."));
            repo.save(new Slang((Long)null, "based", "Confident and authentic opinion", "That take is based."));
            repo.save(new Slang((Long)null, "cringe", "Embarrassing behavior", "That speech was cringe."));
            repo.save(new Slang((Long)null, "shade", "Subtle insult", "She threw shade."));
            repo.save(new Slang((Long)null, "receipts", "Proof or evidence", "Show the receipts."));
            repo.save(new Slang((Long)null, "dry", "Boring or lifeless", "The party was dry."));
            repo.save(new Slang((Long)null, "valid", "Reasonable or acceptable", "That excuse is valid."));
            repo.save(new Slang((Long)null, "pressed", "Overly bothered", "Why are you so pressed?"));
            repo.save(new Slang((Long)null, "glow up", "Major improvement", "Her glow up is unreal."));
            repo.save(new Slang((Long)null, "side eye", "Judgmental look", "That comment got a side eye."));
            repo.save(new Slang((Long)null, "send it", "Go all in", "Let’s send it."));
            repo.save(new Slang((Long)null, "caught in 4k", "Caught with evidence", "You got caught in 4k."));
            repo.save(new Slang((Long)null, "out of pocket", "Inappropriate", "That joke was out of pocket."));
            repo.save(new Slang((Long)null, "core memory", "Memorable moment", "That trip was a core memory."));
            repo.save(new Slang((Long)null, "brain rot", "Overconsuming bad content", "TikTok gave me brain rot."));
            repo.save(new Slang((Long)null, "era", "Phase of life", "I’m in my gym era."));
            repo.save(new Slang((Long)null, "it’s giving", "It feels like", "It’s giving confidence."));
            repo.save(new Slang((Long)null, "shook", "Surprised or shocked", "I was shook."));
            repo.save(new Slang((Long)null, "folded", "Gave up easily", "He folded under pressure."));
            repo.save(new Slang((Long)null, "locked in", "Fully focused", "I’m locked in this semester."));
            repo.save(new Slang((Long)null, "chef’s kiss", "Perfect", "That ending was chef’s kiss."));
            repo.save(new Slang((Long)null, "copy", "Understood", "Say less, copy."));
            repo.save(new Slang((Long)null, "say less", "I understand", "You want pizza? Say less."));
            repo.save(new Slang((Long)null, "nah that’s wild", "Extreme disbelief", "You did WHAT? Nah that’s wild."));
            repo.save(new Slang((Long)null, "final boss", "The hardest challenge", "That exam was the final boss."));
            repo.save(new Slang((Long)null, "skibidi", "Absurd viral meme phrase", "Bro keeps saying skibidi in class."));
            repo.save(new Slang((Long)null, "gyat", "Exclamation of admiration", "GYAT bro chill."));
            repo.save(new Slang((Long)null, "ope", "Polite midwestern slip-up", "Ope—didn’t mean to bump you."));
            repo.save(new Slang((Long)null, "boomer", "Outdated person or behavior", "Okay boomer."));
            repo.save(new Slang((Long)null, "sigma", "Self-reliant or lone-wolf energy", "He’s giving sigma vibes."));
            repo.save(new Slang((Long)null, "glazed", "Distracted or blank-faced", "She looked glazed in math class."));
            repo.save(new Slang((Long)null, "midwit", "Someone average who overestimates intelligence", "That take is such a midwit thing."));
            repo.save(new Slang((Long)null, "camp", "So bad it’s entertaining", "That outfit is camp."));
            repo.save(new Slang((Long)null, "snatched", "Well-fitted or flattering", "Her jacket is snatched."));
            repo.save(new Slang((Long)null, "serve", "To deliver style or confidence", "She served at that event."));
            repo.save(new Slang((Long)null, "yeet", "Throw something forcefully", "He yeeted his backpack on the couch."));
            repo.save(new Slang((Long)null, "slay", "Perform exceptionally", "She slayed that solo."));
            repo.save(new Slang((Long)null, "gooning", "Lost in sensory distraction", "You’ve been gooning on TikTok for hours."));
            repo.save(new Slang((Long)null, "bag secured", "Achieving a goal or earning money", "Job offer came in—bag secured."));
            repo.save(new Slang((Long)null, "bag fumbled", "Lost an opportunity", "Bro fumbled the bag big time."));
            repo.save(new Slang((Long)null, "built different", "Exceptional talent or strength", "That goalie is built different."));
            repo.save(new Slang((Long)null, "clout", "Social influence or status", "People only do that for clout."));
            repo.save(new Slang((Long)null, "clout chasing", "Seeking attention through association", "He keeps clout chasing creators."));
            repo.save(new Slang((Long)null, "bozo", "Foolish or goofy person", "Stop acting like a bozo."));
            repo.save(new Slang((Long)null, "brick", "Freezing cold weather", "It’s brick outside."));
            repo.save(new Slang((Long)null, "pull up", "Arrive or come over", "Pull up after school."));
            repo.save(new Slang((Long)null, "spin back", "Reattempt or retaliate", "Spin back on that quiz."));
            repo.save(new Slang((Long)null, "fr", "For real", "You’re late again? Fr."));
            repo.save(new Slang((Long)null, "glazing", "Excessive praise or attention", "Stop glazing the teacher."));
            repo.save(new Slang((Long)null, "swerve", "Avoid or reject", "I tried asking—she swerved."));
            repo.save(new Slang((Long)null, "pulling", "Successfully attracting someone", "Bro is pulling lately."));
            repo.save(new Slang((Long)null, "low vibrational", "Negative or draining energy", "Their argument was low vibrational."));
            repo.save(new Slang((Long)null, "pop off", "React strongly or aggressively", "The crowd popped off at that goal."));
            repo.save(new Slang((Long)null, "suspect behavior", "Questionable decision", "Leaving early was suspect behavior."));
            repo.save(new Slang((Long)null, "caught lacking", "Unprepared or vulnerable", "He got caught lacking in gym."));
            repo.save(new Slang((Long)null, "washed", "Past their prime or outdated", "That franchise is washed."));
            repo.save(new Slang((Long)null, "mobile", "Easily moved or active", "Bro is mobile on defense."));
            repo.save(new Slang((Long)null, "brutal", "Harsh honesty", "Her review was brutal."));
            repo.save(new Slang((Long)null, "zesty", "Feminine or flamboyant energy", "His movements were zesty."));
            repo.save(new Slang((Long)null, "malding", "Mad and balding (metaphorically)", "He’s malding over the exam."));
            repo.save(new Slang((Long)null, "cope", "Accept disappointment", "It is what it is—cope."));
            repo.save(new Slang((Long)null, "peak", "Best possible", "That track was peak."));
            repo.save(new Slang((Long)null, "overclocked", "Performing beyond normal limits", "My brain is overclocked studying."));
            repo.save(new Slang((Long)null, "rent free", "Living in someone's mind", "I’m living rent free in his head."));
            repo.save(new Slang((Long)null, "gatekeeping", "Withholding knowledge", "Stop gatekeeping skincare."));
            repo.save(new Slang((Long)null, "booster", "Someone who steals retail items", "Security caught a booster at the mall."));
            repo.save(new Slang((Long)null, "understood the assignment", "Performed perfectly", "She understood the assignment."));
            repo.save(new Slang((Long)null, "no notes", "Perfect execution", "Her speech? No notes."));
            repo.save(new Slang((Long)null, "ratio proof", "Immune to online backlash", "That meme is ratio proof."));
            repo.save(new Slang((Long)null, "over it", "Done with something emotionally", "After today, I'm over it."));
            repo.save(new Slang((Long)null, "on god", "Strong affirmation of truth", "That test was impossible on god."));
            repo.save(new Slang((Long)null, "joker moment", "Time of snapping or frustration", "Studying at 3AM is my joker moment."));
            repo.save(new Slang((Long)null, "zoomies", "Sudden burst of chaotic energy", "My dog had the zoomies at midnight."));
            repo.save(new Slang((Long)null, "plot armor", "Unlikely protection from failure", "He survived with pure plot armor."));
            repo.save(new Slang((Long)null, "underleveled", "Not prepared enough for challenge", "I was underleveled for that chem exam."));
            repo.save(new Slang((Long)null, "overleveled", "Stronger than required", "I'm overleveled for first-year courses."));
            repo.save(new Slang((Long)null, "low diff", "Won with minimal effort", "Study group beat that test low diff."));
            repo.save(new Slang((Long)null, "high diff", "Hard fight or challenge", "Compsci was high diff this term."));
            repo.save(new Slang((Long)null, "full send", "Commit fully regardless of consequences", "No study plan, full send tomorrow."));
            repo.save(new Slang((Long)null, "shielded", "Protected socially or emotionally", "Her friends keep her shielded from drama."));
            repo.save(new Slang((Long)null, "cooked politically", "Ruined reputation in group dynamics", "He's cooked politically after that speech."));
            repo.save(new Slang((Long)null, "rolled", "Dominated or defeated easily", "Our team got rolled in playoffs."));
            repo.save(new Slang((Long)null, "camped", "Targeted repeatedly", "The boss camped me the whole round."));
            repo.save(new Slang((Long)null, "low income arc", "Phase of financial struggle", "Summer job ended—entering my low income arc."));
            repo.save(new Slang((Long)null, "overstimmed", "Mentally overwhelmed by stimuli", "Mall crowds get me overstimmed."));
            repo.save(new Slang((Long)null, "vibeless", "Lacking good atmosphere", "The party was vibeless after midnight."));
            repo.save(new Slang((Long)null, "on demon time", "Acting boldly and aggressively", "He was on demon time during finals."));
            repo.save(new Slang((Long)null, "no thoughts head empty", "Lack of thinking or awareness", "Post-exam I’m no thoughts head empty."));
            repo.save(new Slang((Long)null, "brain go brrr", "Mind acting without rational processing", "Cold coffee makes the brain go brrr."));
            repo.save(new Slang((Long)null, "outside", "Socially active", "Everyone’s outside this weekend."));
            repo.save(new Slang((Long)null, "inside era", "Period of staying home often", "I'm in my inside era now."));
            repo.save(new Slang((Long)null, "main quest", "Primary life objective", "Graduating is the main quest."));
            repo.save(new Slang((Long)null, "side quest", "Non-essential goal or task", "Getting boba was a side quest today."));
            repo.save(new Slang((Long)null, "NPC energy", "Passive or unaware vibe", "The cashier had NPC energy."));
            repo.save(new Slang((Long)null, "protagonist syndrome", "Belief life revolves around oneself", "Group projects bring out protagonist syndrome."));
            repo.save(new Slang((Long)null, "buffed", "Enhanced or improved", "He got buffed after joining the gym."));
            repo.save(new Slang((Long)null, "nerfed", "Weakened or made worse", "Tuition got nerfed? No, tuition got buffed."));
            repo.save(new Slang((Long)null, "skill issue", "Blaming failure on lack of skill", "You dropped it? Skill issue."));
            repo.save(new Slang((Long)null, "cope strat", "Strategy to deal with disappointment", "Retail therapy is my cope strat."));
            repo.save(new Slang((Long)null, "ratio immune", "Cannot be ratioed online", "That meme is ratio immune."));
            repo.save(new Slang((Long)null, "wifi warrior", "Brave online, timid in person", "He only talks back as a wifi warrior."));
            repo.save(new Slang((Long)null, "brick phone era", "Time without good tech", "Middle school was my brick phone era."));
            repo.save(new Slang((Long)null, "error 404", "Emotion or logic not found", "Sleeping schedule? Error 404."));
            repo.save(new Slang((Long)null, "downloaded patch", "Improved suddenly overnight", "She slept 10 hours and downloaded a patch."));
            repo.save(new Slang((Long)null, "patched up", "Recovered from crisis", "After therapy he's patched up."));
            repo.save(new Slang((Long)null, "boosted stats", "Increased performance under conditions", "Caffeine gives boosted stats."));
            repo.save(new Slang((Long)null, "prestige", "Advance after completion of stage", "Graduating is like prestige IRL."));
            repo.save(new Slang((Long)null, "zero drip", "No style at all", "The outfit had zero drip."));
            repo.save(new Slang((Long)null, "deflated", "Emotionally exhausted", "After the exam I felt deflated."));
            repo.save(new Slang((Long)null, "inflated", "Overly confident", "He walked out inflated after question 1."));
            repo.save(new Slang((Long)null, "AFK", "Absent mentally or physically", "Sorry I was AFK during that lecture."));
            repo.save(new Slang((Long)null, "irl buff", "Skill that helps in real world", "Cooking is an irl buff."));
            repo.save(new Slang((Long)null, "mid arc", "Period of mediocrity", "This semester was a mid arc."));
            repo.save(new Slang((Long)null, "god run", "Unexpected perfect performance", "My math quiz was a god run."));
            repo.save(new Slang((Long)null, "low roll", "Worst possible outcome", "I low rolled on job interviews."));
            repo.save(new Slang((Long)null, "high roll", "Lucky or fortunate result", "Study guesses were a high roll."));
            repo.save(new Slang((Long)null, "tutorial mode", "Extremely easy conditions", "Group project was tutorial mode for him."));
            repo.save(new Slang((Long)null, "hard mode", "Challenging conditions", "Working two jobs is hard mode."));
            repo.save(new Slang((Long)null, "night mode", "Late-night productivity state", "Assignments unlocked night mode."));
            repo.save(new Slang((Long)null, "speedrun", "Complete task very quickly", "I speedran the homework."));
            repo.save(new Slang((Long)null, "slowrun", "Complete task unnecessarily slow", "He slowran the presentation."));
            repo.save(new Slang((Long)null, "chilling", "Relaxing with no urgency", "I'm chilling till midterms."));
            repo.save(new Slang((Long)null, "cracked", "Exceptional skill or performance", "He's cracked at coding."));
            repo.save(new Slang((Long)null, "decayed", "Loss of previous ability", "My Spanish decayed over summer."));
            repo.save(new Slang((Long)null, "maxed out", "Reached capacity", "Brain is maxed out today."));
            repo.save(new Slang((Long)null, "no cooldown", "Acting repeatedly without pause", "He kept complaining with no cooldown."));
        };
    }
}